module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    'react-native-reanimated/plugin',
    [
      'module-resolver',
      {
        root: ['./'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          '@/assets': ['./src/assets'],
          '@/assets/*': ['./src/assets/*'],
          '@/components': ['./src/components'],
          '@/components/*': ['./src/components/*'],
          '@/configs': ['./src/configs'],
          '@/configs/*': ['./src/configs/*'],
          '@/constants': ['./src/constants'],
          '@/constants/*': ['./src/constants/*'],
          '@/core': ['./src/core'],
          '@/core/*': ['./src/core/*'],
          '@/hooks': ['./src/hooks'],
          '@/hooks/*': ['./src/hooks/*'],
          '@/types': ['./src/types'],
          '@/types/*': ['./src/types/*'],
          '@/navigators': ['./src/navigators'],
          '@/navigators/*': ['./src/navigators/*'],
          '@/repositories': ['./src/repositories'],
          '@/repositories/*': ['./src/repositories/*'],
          '@/scenes': ['./src/scenes'],
          '@/scenes/*': ['./src/scenes/*'],
          '@/services': ['./src/services'],
          '@/services/*': ['./src/services/*'],
          '@/stores': ['./src/stores'],
          '@/stores/*': ['./src/stores/*'],
          '@/theme': ['./src/theme'],
          '@/theme/*': ['./src/theme/*'],
          '@/utils': ['./src/utils'],
          '@/utils/*': ['./src/utils/*'],
        },
      },
    ],
  ],
}
